### ISSUE TITLE
Dwarf female image

### ISSUE THREAD

**Issue by Carlo-F** [mchekin/rpg#63]
It's identical to Dwarf male.

**Comment by mchekin** [comment]
@Carlo-F 

Thank you for reaching out. 

But we already have an issue open regarding images.
[Artist needed: in order to create better in-game images ](https://github.com/mchekin/rpg/issues/3)

Unfortunately, I am not an artist so I cannot create the art work myself and only images under [CC0 ](https://creativecommons.org/share-your-work/public-domain/cc0/) license can be accepted since this is an open-source project.

If you have better CC0 artwork or you can create it yourself, your contribution would be greatly appreciated.

**Comment by Carlo-F** [comment]
@mchekin 

Ok, unfortunately, i'm not an artist too.
