### ISSUE TITLE
Dockerize the application.

### ISSUE THREAD

**Issue by mchekin** [mchekin/rpg#64]
Adding ability to run the application in a dockerized environment using Docker Compose.

Basic version with 3 Docker containers:
- nginx
- php-fpm
- mysql

**Comment by ricardosierra** [comment]
HI.. i have this

**Comment by ricardosierra** [comment]
https://github.com/mchekin/rpg/pull/71/

Can you see ? What do you fthink ?
The docker compose is pointed at the dockerhub because of its performance but exactly it is configured in the docker /

The other services I commented on because I thought it wouldn't be necessary, but if you want to use the elastic, you need to uncomment it and add the line to .env
ELASTIC_SEARCH_HOST=elasticsearch: 9200

**Comment by mchekin** [comment]
@ricardosierra 

Actually I have assigned it to myself 15 days ago https://github.com/mchekin/rpg/issues/64#event-3786103387 :)
And I have been working on it in the https://github.com/mchekin/rpg/tree/dockerize-the-app branch.

But that is OK because we can merge your version when it is ready and then merge any additional changes, if needed, from my version.

**Comment by ricardosierra** [comment]
:) obrigado. Seu jogo de RPG ficou foda pra caralho. Parabéns

**Comment by ricardosierra** [comment]
Sorry...

Your RPG game is Very Very good. Congratilations. Thanks

**Comment by mchekin** [comment]
@ricardosierra 

Thank you very much!

I hope we can cooperate on it and make it really great!

**Comment by mchekin** [comment]
@ricardosierra 

But currently there is an issue with the pull-request https://github.com/mchekin/rpg/pull/71#issuecomment-703801317

**Comment by mchekin** [comment]
@ricardosierra 

Thank you for your contribution.
I took some inspiration from your pull request, but since there was no answer for sometime in this thread I continued with my own branch and merged it.
https://github.com/mchekin/rpg/pull/72

Please tell me if you think there any issues with it.
